Repository kinhosz/Appel, pull requests merged in 2023-07, with the labels that each got.

#1 Project Structure
  README.md
  assets/readme.md
  bin/readme.md
  docs/project_structure.md
  include/readme.md
  src/readme.md
Labels: documentation, enhancement

#12 Point
  include/geometry/point.h
  include/readme.md
  src/geometry/point.cpp
  src/readme.md
Labels: enhancement

#13 feat(makefile): compile, run & CI
  .github/workflows/ci.yaml
  .gitignore
  Makefile
  README.md
  bin/readme.md
  scripts/compile.mk
  scripts/global.mk
  scripts/linux.mk
  scripts/run.mk
  scripts/tests.mk
  scripts/unitTest.mk
  scripts/windows.mk
  tests/geometry/point.cpp
  tests/geometry/vetor.cpp
Labels: enhancement

#14 feat: add light.h, light.cpp, color.h & color.cpp
  include/entity/light.h
  include/graphic/color.h
  src/entity/light.cpp
  src/graphic/color.cpp
Labels: enhancement

#15 Hotfix/ci includes
  Makefile
  include/entity/light.h
  include/graphic/color.h
  scripts/compile.mk
  scripts/global.mk
  scripts/linux.mk
  scripts/windows.mk
  src/entity/light.cpp
  src/geometry/point.cpp
  src/geometry/vetor.cpp
  src/graphic/color.cpp
  tests/geometry/point.cpp
  tests/geometry/vetor.cpp
Labels: bug

#16 refactor: use only camel case convention
  include/geometry/vetor.h
  src/geometry/point.cpp
  src/geometry/vetor.cpp
Labels: enhancement

#17 feat: add tests and some adjusts/improvements
  include/geometry/point.h
  include/geometry/utils.h
  include/geometry/vetor.h
  src/geometry/point.cpp
  src/geometry/utils.cpp
  src/geometry/vetor.cpp
  tests/entity/light.cpp
  tests/geometry/point.cpp
  tests/geometry/vetor.cpp
  tests/graphic/color.cpp
Labels: bug, enhancement

#18 Feat/camera
  include/geometry/vetor.h
  include/graphic/camera.h
  src/geometry/vetor.cpp
  src/graphic/camera.cpp
  tests/graphic/camera.cpp
Labels: enhancement
