Repository kinhosz/Appel, pull requests merged in 2023-08, with the labels that each got.

#22 feat(ray): add ray & 3rd changes
  include/geometry/ray.h
  include/geometry/utils.h
  include/geometry/vetor.h
  scripts/global.mk
  src/geometry/ray.cpp
  src/geometry/utils.cpp
  src/geometry/vetor.cpp
  tests/geometry/ray.cpp
  tests/geometry/vetor.cpp
Labels: bug, enhancement

#54 fix(yaml)
  .github/workflows/semVer.yaml
Labels: documentation

#24 Feat/box
  include/geometry/box.h
  include/graphic/color.h
  include/graphic/pixel.h
  src/geometry/box.cpp
  src/graphic/color.cpp
  src/graphic/pixel.cpp
  tests/entity/light.cpp
  tests/geometry/box.cpp
  tests/graphic/color.cpp
  tests/graphic/pixel.cpp
Labels: enhancement

#63 Docs/project-structure
  docs/project_structure.md
Labels: documentation

#62 Feat/plane
  include/entity/plane.h
  src/entity/plane.cpp
  tests/entity/plane.cpp
Labels: enhancement

#61 Feat/sphere
  include/entity/sphere.h
  src/entity/sphere.cpp
  tests/entity/sphere.cpp
  tests/geometry/ray.cpp
Labels: enhancement

#55 feat(frame): add & test
  include/graphic/frame.h
  src/graphic/frame.cpp
  tests/graphic/frame.cpp
Labels: enhancement

#64 Feat/scene
  include/entity/light.h
  include/entity/scene.h
  include/graphic/color.h
  src/entity/light.cpp
  src/entity/scene.cpp
  src/graphic/color.cpp
  tests/entity/scene.cpp
Labels: enhancement

#79 Feat/box intersect
  include/entity/box.h
  include/entity/plane.h
  include/entity/scene.h
  include/entity/sphere.h
  include/geometry/surfaceIntersection.h
  include/geometry/utils.h
  src/entity/box.cpp
  src/geometry/surfaceIntersection.cpp
  tests/entity/box.cpp
  tests/geometry/box.cpp
  tests/geometry/surfaceIntersection.cpp
Labels: enhancement, help wanted

#81 feat(lib): add SFML 2.6.0
  .github/workflows/ci.yaml
  .gitignore
  Makefile
  README.md
  docs/project_structure.md
  scripts/compile.mk
  scripts/dependencies/sfml.mk
  scripts/global.mk
  scripts/install.mk
  scripts/linux.mk
  scripts/run.mk
  tests/SFML/image.cpp
Labels: enhancement

#83 Feat/triangular mesh
  include/entity/triangularMesh.h
  include/geometry/triangle.h
  include/geometry/utils.h
  src/entity/triangularMesh.cpp
  src/geometry/triangle.cpp
  src/geometry/utils.cpp
  tests/entity/triangularMesh.cpp
Labels: enhancement

#87 feat: add triangularMesh.intersect & help functions
  include/entity/box.h
  include/entity/triangularMesh.h
  include/geometry/triangle.h
  include/geometry/utils.h
  include/geometry/vetor.h
  scripts/tests.mk
  src/entity/triangularMesh.cpp
  src/geometry/triangle.cpp
  src/geometry/utils.cpp
  src/geometry/vetor.cpp
  tests/entity/triangularMesh/intersect.cpp
  tests/geometry/gaussElimination.cpp
  tests/geometry/triangle/intersect.cpp
  tests/geometry/triangle/isInside.cpp
Labels: enhancement

#89 feat: ray casting
  include/entity/scene.h
  src/entity/scene.cpp
Labels: enhancement

#91 feat: camera.take + scene refactor
  assets/outputs/version_00/image_00.png
  assets/outputs/version_00/image_01.png
  assets/outputs/version_00/image_02.png
  assets/outputs/version_00/image_03.png
  assets/outputs/version_00/image_04.png
  include/entity/scene.h
  include/graphic/camera.h
  include/graphic/color.h
  include/graphic/utils.h
  src/entity/box.cpp
  src/entity/scene.cpp
  src/geometry/triangle.cpp
  src/geometry/utils.cpp
  src/graphic/camera.cpp
  src/graphic/color.cpp
  src/graphic/frame.cpp
  src/graphic/utils.cpp
  tests/entity/scene.cpp
  tests/graphic/frame.cpp
  tests/project_v0/version_00.cpp
Labels: enhancement

#86 Feat/planeIntersection
  assets/outputs/version_01/image_00.png
  assets/outputs/version_01/image_01.png
  assets/outputs/version_01/image_02.png
  assets/outputs/version_01/image_03.png
  assets/outputs/version_01/image_04.png
  assets/outputs/version_01/image_05.png
  include/entity/plane.h
  src/entity/plane.cpp
  src/geometry/triangle.cpp
  tests/project_v0/version_01.cpp
Labels: enhancement

#96 Docs/projectStructure
  docs/project_structure.md
Labels: documentation

#100 Docs/readme
  README.md
  assets/outputs/project_v1/version_00/image_00.png
  assets/outputs/project_v1/version_00/image_01.png
  assets/outputs/project_v1/version_00/image_02.png
  assets/outputs/project_v1/version_00/image_03.png
  assets/outputs/project_v1/version_00/image_04.png
  assets/outputs/project_v1/version_00/image_05.png
  assets/outputs/project_v1/version_01/image_00.png
  assets/outputs/project_v1/version_01/image_01.png
  assets/outputs/project_v1/version_01/image_02.png
  assets/outputs/project_v1/version_01/image_03.png
  assets/outputs/project_v1/version_01/image_04.png
  assets/outputs/project_v1/version_01/image_05.png
  assets/outputs/project_v1/version_02/image_00.png
  assets/outputs/project_v1/version_02/image_01.png
  assets/outputs/project_v1/version_02/image_02.png
  assets/outputs/project_v1/version_02/image_03.png
  assets/outputs/project_v1/version_02/image_04.png
  assets/outputs/project_v1/version_02/image_05.png
  assets/outputs/project_v1/version_03/image_00.png
  assets/outputs/project_v1/version_03/image_01.png
  assets/outputs/project_v1/version_03/image_02.png
  assets/outputs/project_v1/version_03/image_03.png
  assets/outputs/project_v1/version_03/image_04.png
  assets/outputs/project_v1/version_03/image_05.png
  tests/project_v1/version_00.cpp
  tests/project_v1/version_01.cpp
  tests/project_v1/version_02.cpp
  tests/project_v1/version_03.cpp
Labels: documentation
